//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using PropHunt.Mixed.Commands;


namespace PropHunt.Generated
{
    [BurstCompile]
    public struct PropHuntMixedCommandsSceneLoadCommandSerializer : IComponentData, IRpcCommandSerializer<PropHunt.Mixed.Commands.SceneLoadCommand>
    {
        public void Serialize(ref DataStreamWriter writer, in PropHunt.Mixed.Commands.SceneLoadCommand data)
        {
            writer.WriteFixedString64(data.loadScene);
            writer.WriteFixedString64(data.unloadScene);
        }

        public void Deserialize(ref DataStreamReader reader, ref PropHunt.Mixed.Commands.SceneLoadCommand data)
        {
            data.loadScene = reader.ReadFixedString64();
            data.unloadScene = reader.ReadFixedString64();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<PropHuntMixedCommandsSceneLoadCommandSerializer, PropHunt.Mixed.Commands.SceneLoadCommand>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class PropHuntMixedCommandsSceneLoadCommandRpcCommandRequestSystem : RpcCommandRequestSystem<PropHuntMixedCommandsSceneLoadCommandSerializer, PropHunt.Mixed.Commands.SceneLoadCommand>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
