//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;
using PropHunt.Mixed.Commands;


namespace PropHunt.Generated
{
    [BurstCompile]
    public struct PropHuntMixedCommandsTeleportPlayerCommandSerializer : IComponentData, IRpcCommandSerializer<PropHunt.Mixed.Commands.TeleportPlayerCommand>
    {
        public void Serialize(ref DataStreamWriter writer, in PropHunt.Mixed.Commands.TeleportPlayerCommand data)
        {
            writer.WriteFloat(data.position.x);
            writer.WriteFloat(data.position.y);
            writer.WriteFloat(data.position.z);
            writer.WriteFloat(data.attitude.value.x);
            writer.WriteFloat(data.attitude.value.y);
            writer.WriteFloat(data.attitude.value.z);
            writer.WriteFloat(data.attitude.value.w);
            writer.WriteInt((int) data.playerId);
        }

        public void Deserialize(ref DataStreamReader reader, ref PropHunt.Mixed.Commands.TeleportPlayerCommand data)
        {
            data.position.x = reader.ReadFloat();
            data.position.y = reader.ReadFloat();
            data.position.z = reader.ReadFloat();
            data.attitude.value.x = reader.ReadFloat();
            data.attitude.value.y = reader.ReadFloat();
            data.attitude.value.z = reader.ReadFloat();
            data.attitude.value.w = reader.ReadFloat();
            data.playerId = (int) reader.ReadInt();
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(RpcExecutor.ExecuteDelegate))]
        private static void InvokeExecute(ref RpcExecutor.Parameters parameters)
        {
            RpcExecutor.ExecuteCreateRequestComponent<PropHuntMixedCommandsTeleportPlayerCommandSerializer, PropHunt.Mixed.Commands.TeleportPlayerCommand>(ref parameters);
        }

        static PortableFunctionPointer<RpcExecutor.ExecuteDelegate> InvokeExecuteFunctionPointer =
            new PortableFunctionPointer<RpcExecutor.ExecuteDelegate>(InvokeExecute);
        public PortableFunctionPointer<RpcExecutor.ExecuteDelegate> CompileExecute()
        {
            return InvokeExecuteFunctionPointer;
        }
    }
    class PropHuntMixedCommandsTeleportPlayerCommandRpcCommandRequestSystem : RpcCommandRequestSystem<PropHuntMixedCommandsTeleportPlayerCommandSerializer, PropHunt.Mixed.Commands.TeleportPlayerCommand>
    {
        [BurstCompile]
        protected struct SendRpc : IJobEntityBatch
        {
            public SendRpcData data;
            public void Execute(ArchetypeChunk chunk, int orderIndex)
            {
                data.Execute(chunk, orderIndex);
            }
        }
        protected override void OnUpdate()
        {
            var sendJob = new SendRpc{data = InitJobData()};
            ScheduleJobData(sendJob);
        }
    }
}
